package test.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public AdminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAdminIsNull() {
            addCriterion("admin is null");
            return (Criteria) this;
        }

        public Criteria andAdminIsNotNull() {
            addCriterion("admin is not null");
            return (Criteria) this;
        }

        public Criteria andAdminEqualTo(String value) {
            addCriterion("admin =", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotEqualTo(String value) {
            addCriterion("admin <>", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThan(String value) {
            addCriterion("admin >", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThanOrEqualTo(String value) {
            addCriterion("admin >=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThan(String value) {
            addCriterion("admin <", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThanOrEqualTo(String value) {
            addCriterion("admin <=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLike(String value) {
            addCriterion("admin like", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotLike(String value) {
            addCriterion("admin not like", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminIn(List<String> values) {
            addCriterion("admin in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotIn(List<String> values) {
            addCriterion("admin not in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminBetween(String value1, String value2) {
            addCriterion("admin between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotBetween(String value1, String value2) {
            addCriterion("admin not between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andLastLoginIsNull() {
            addCriterion("last_login is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIsNotNull() {
            addCriterion("last_login is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginEqualTo(Date value) {
            addCriterion("last_login =", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotEqualTo(Date value) {
            addCriterion("last_login <>", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginGreaterThan(Date value) {
            addCriterion("last_login >", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login >=", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginLessThan(Date value) {
            addCriterion("last_login <", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginLessThanOrEqualTo(Date value) {
            addCriterion("last_login <=", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginIn(List<Date> values) {
            addCriterion("last_login in", values, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotIn(List<Date> values) {
            addCriterion("last_login not in", values, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginBetween(Date value1, Date value2) {
            addCriterion("last_login between", value1, value2, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotBetween(Date value1, Date value2) {
            addCriterion("last_login not between", value1, value2, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastIpIsNull() {
            addCriterion("last_ip is null");
            return (Criteria) this;
        }

        public Criteria andLastIpIsNotNull() {
            addCriterion("last_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLastIpEqualTo(String value) {
            addCriterion("last_ip =", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpNotEqualTo(String value) {
            addCriterion("last_ip <>", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpGreaterThan(String value) {
            addCriterion("last_ip >", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpGreaterThanOrEqualTo(String value) {
            addCriterion("last_ip >=", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpLessThan(String value) {
            addCriterion("last_ip <", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpLessThanOrEqualTo(String value) {
            addCriterion("last_ip <=", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpLike(String value) {
            addCriterion("last_ip like", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpNotLike(String value) {
            addCriterion("last_ip not like", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpIn(List<String> values) {
            addCriterion("last_ip in", values, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpNotIn(List<String> values) {
            addCriterion("last_ip not in", values, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpBetween(String value1, String value2) {
            addCriterion("last_ip between", value1, value2, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpNotBetween(String value1, String value2) {
            addCriterion("last_ip not between", value1, value2, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLoginTimesIsNull() {
            addCriterion("login_times is null");
            return (Criteria) this;
        }

        public Criteria andLoginTimesIsNotNull() {
            addCriterion("login_times is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTimesEqualTo(Integer value) {
            addCriterion("login_times =", value, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesNotEqualTo(Integer value) {
            addCriterion("login_times <>", value, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesGreaterThan(Integer value) {
            addCriterion("login_times >", value, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_times >=", value, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesLessThan(Integer value) {
            addCriterion("login_times <", value, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesLessThanOrEqualTo(Integer value) {
            addCriterion("login_times <=", value, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesIn(List<Integer> values) {
            addCriterion("login_times in", values, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesNotIn(List<Integer> values) {
            addCriterion("login_times not in", values, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesBetween(Integer value1, Integer value2) {
            addCriterion("login_times between", value1, value2, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andLoginTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("login_times not between", value1, value2, "loginTimes");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("realname is null");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("realname is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("realname =", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("realname <>", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("realname >", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("realname >=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("realname <", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("realname <=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("realname like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("realname not like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameIn(List<String> values) {
            addCriterion("realname in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotIn(List<String> values) {
            addCriterion("realname not in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("realname between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("realname not between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRank0IsNull() {
            addCriterion("rank0 is null");
            return (Criteria) this;
        }

        public Criteria andRank0IsNotNull() {
            addCriterion("rank0 is not null");
            return (Criteria) this;
        }

        public Criteria andRank0EqualTo(Boolean value) {
            addCriterion("rank0 =", value, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0NotEqualTo(Boolean value) {
            addCriterion("rank0 <>", value, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0GreaterThan(Boolean value) {
            addCriterion("rank0 >", value, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0GreaterThanOrEqualTo(Boolean value) {
            addCriterion("rank0 >=", value, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0LessThan(Boolean value) {
            addCriterion("rank0 <", value, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0LessThanOrEqualTo(Boolean value) {
            addCriterion("rank0 <=", value, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0In(List<Boolean> values) {
            addCriterion("rank0 in", values, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0NotIn(List<Boolean> values) {
            addCriterion("rank0 not in", values, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0Between(Boolean value1, Boolean value2) {
            addCriterion("rank0 between", value1, value2, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank0NotBetween(Boolean value1, Boolean value2) {
            addCriterion("rank0 not between", value1, value2, "rank0");
            return (Criteria) this;
        }

        public Criteria andRank1IsNull() {
            addCriterion("rank1 is null");
            return (Criteria) this;
        }

        public Criteria andRank1IsNotNull() {
            addCriterion("rank1 is not null");
            return (Criteria) this;
        }

        public Criteria andRank1EqualTo(Boolean value) {
            addCriterion("rank1 =", value, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1NotEqualTo(Boolean value) {
            addCriterion("rank1 <>", value, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1GreaterThan(Boolean value) {
            addCriterion("rank1 >", value, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1GreaterThanOrEqualTo(Boolean value) {
            addCriterion("rank1 >=", value, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1LessThan(Boolean value) {
            addCriterion("rank1 <", value, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1LessThanOrEqualTo(Boolean value) {
            addCriterion("rank1 <=", value, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1In(List<Boolean> values) {
            addCriterion("rank1 in", values, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1NotIn(List<Boolean> values) {
            addCriterion("rank1 not in", values, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1Between(Boolean value1, Boolean value2) {
            addCriterion("rank1 between", value1, value2, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank1NotBetween(Boolean value1, Boolean value2) {
            addCriterion("rank1 not between", value1, value2, "rank1");
            return (Criteria) this;
        }

        public Criteria andRank2IsNull() {
            addCriterion("rank2 is null");
            return (Criteria) this;
        }

        public Criteria andRank2IsNotNull() {
            addCriterion("rank2 is not null");
            return (Criteria) this;
        }

        public Criteria andRank2EqualTo(Boolean value) {
            addCriterion("rank2 =", value, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2NotEqualTo(Boolean value) {
            addCriterion("rank2 <>", value, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2GreaterThan(Boolean value) {
            addCriterion("rank2 >", value, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2GreaterThanOrEqualTo(Boolean value) {
            addCriterion("rank2 >=", value, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2LessThan(Boolean value) {
            addCriterion("rank2 <", value, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2LessThanOrEqualTo(Boolean value) {
            addCriterion("rank2 <=", value, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2In(List<Boolean> values) {
            addCriterion("rank2 in", values, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2NotIn(List<Boolean> values) {
            addCriterion("rank2 not in", values, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2Between(Boolean value1, Boolean value2) {
            addCriterion("rank2 between", value1, value2, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank2NotBetween(Boolean value1, Boolean value2) {
            addCriterion("rank2 not between", value1, value2, "rank2");
            return (Criteria) this;
        }

        public Criteria andRank3IsNull() {
            addCriterion("rank3 is null");
            return (Criteria) this;
        }

        public Criteria andRank3IsNotNull() {
            addCriterion("rank3 is not null");
            return (Criteria) this;
        }

        public Criteria andRank3EqualTo(Boolean value) {
            addCriterion("rank3 =", value, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3NotEqualTo(Boolean value) {
            addCriterion("rank3 <>", value, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3GreaterThan(Boolean value) {
            addCriterion("rank3 >", value, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3GreaterThanOrEqualTo(Boolean value) {
            addCriterion("rank3 >=", value, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3LessThan(Boolean value) {
            addCriterion("rank3 <", value, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3LessThanOrEqualTo(Boolean value) {
            addCriterion("rank3 <=", value, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3In(List<Boolean> values) {
            addCriterion("rank3 in", values, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3NotIn(List<Boolean> values) {
            addCriterion("rank3 not in", values, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3Between(Boolean value1, Boolean value2) {
            addCriterion("rank3 between", value1, value2, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank3NotBetween(Boolean value1, Boolean value2) {
            addCriterion("rank3 not between", value1, value2, "rank3");
            return (Criteria) this;
        }

        public Criteria andRank4IsNull() {
            addCriterion("rank4 is null");
            return (Criteria) this;
        }

        public Criteria andRank4IsNotNull() {
            addCriterion("rank4 is not null");
            return (Criteria) this;
        }

        public Criteria andRank4EqualTo(Boolean value) {
            addCriterion("rank4 =", value, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4NotEqualTo(Boolean value) {
            addCriterion("rank4 <>", value, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4GreaterThan(Boolean value) {
            addCriterion("rank4 >", value, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4GreaterThanOrEqualTo(Boolean value) {
            addCriterion("rank4 >=", value, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4LessThan(Boolean value) {
            addCriterion("rank4 <", value, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4LessThanOrEqualTo(Boolean value) {
            addCriterion("rank4 <=", value, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4In(List<Boolean> values) {
            addCriterion("rank4 in", values, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4NotIn(List<Boolean> values) {
            addCriterion("rank4 not in", values, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4Between(Boolean value1, Boolean value2) {
            addCriterion("rank4 between", value1, value2, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank4NotBetween(Boolean value1, Boolean value2) {
            addCriterion("rank4 not between", value1, value2, "rank4");
            return (Criteria) this;
        }

        public Criteria andRank5IsNull() {
            addCriterion("rank5 is null");
            return (Criteria) this;
        }

        public Criteria andRank5IsNotNull() {
            addCriterion("rank5 is not null");
            return (Criteria) this;
        }

        public Criteria andRank5EqualTo(Boolean value) {
            addCriterion("rank5 =", value, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5NotEqualTo(Boolean value) {
            addCriterion("rank5 <>", value, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5GreaterThan(Boolean value) {
            addCriterion("rank5 >", value, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5GreaterThanOrEqualTo(Boolean value) {
            addCriterion("rank5 >=", value, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5LessThan(Boolean value) {
            addCriterion("rank5 <", value, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5LessThanOrEqualTo(Boolean value) {
            addCriterion("rank5 <=", value, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5In(List<Boolean> values) {
            addCriterion("rank5 in", values, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5NotIn(List<Boolean> values) {
            addCriterion("rank5 not in", values, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5Between(Boolean value1, Boolean value2) {
            addCriterion("rank5 between", value1, value2, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank5NotBetween(Boolean value1, Boolean value2) {
            addCriterion("rank5 not between", value1, value2, "rank5");
            return (Criteria) this;
        }

        public Criteria andRank6IsNull() {
            addCriterion("rank6 is null");
            return (Criteria) this;
        }

        public Criteria andRank6IsNotNull() {
            addCriterion("rank6 is not null");
            return (Criteria) this;
        }

        public Criteria andRank6EqualTo(Boolean value) {
            addCriterion("rank6 =", value, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6NotEqualTo(Boolean value) {
            addCriterion("rank6 <>", value, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6GreaterThan(Boolean value) {
            addCriterion("rank6 >", value, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6GreaterThanOrEqualTo(Boolean value) {
            addCriterion("rank6 >=", value, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6LessThan(Boolean value) {
            addCriterion("rank6 <", value, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6LessThanOrEqualTo(Boolean value) {
            addCriterion("rank6 <=", value, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6In(List<Boolean> values) {
            addCriterion("rank6 in", values, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6NotIn(List<Boolean> values) {
            addCriterion("rank6 not in", values, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6Between(Boolean value1, Boolean value2) {
            addCriterion("rank6 between", value1, value2, "rank6");
            return (Criteria) this;
        }

        public Criteria andRank6NotBetween(Boolean value1, Boolean value2) {
            addCriterion("rank6 not between", value1, value2, "rank6");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}