package test.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admin
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin
     *
     * @mbg.generated
     */
    private String admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.last_login
     *
     * @mbg.generated
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.last_ip
     *
     * @mbg.generated
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.login_times
     *
     * @mbg.generated
     */
    private Integer loginTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.realname
     *
     * @mbg.generated
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.rank0
     *
     * @mbg.generated
     */
    private Boolean rank0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.rank1
     *
     * @mbg.generated
     */
    private Boolean rank1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.rank2
     *
     * @mbg.generated
     */
    private Boolean rank2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.rank3
     *
     * @mbg.generated
     */
    private Boolean rank3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.rank4
     *
     * @mbg.generated
     */
    private Boolean rank4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.rank5
     *
     * @mbg.generated
     */
    private Boolean rank5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.rank6
     *
     * @mbg.generated
     */
    private Boolean rank6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin
     *
     * @return the value of admin.admin
     *
     * @mbg.generated
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin
     *
     * @param admin the value for admin.admin
     *
     * @mbg.generated
     */
    public void setAdmin(String admin) {
        this.admin = admin == null ? null : admin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.last_login
     *
     * @return the value of admin.last_login
     *
     * @mbg.generated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.last_login
     *
     * @param lastLogin the value for admin.last_login
     *
     * @mbg.generated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.last_ip
     *
     * @return the value of admin.last_ip
     *
     * @mbg.generated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.last_ip
     *
     * @param lastIp the value for admin.last_ip
     *
     * @mbg.generated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.login_times
     *
     * @return the value of admin.login_times
     *
     * @mbg.generated
     */
    public Integer getLoginTimes() {
        return loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.login_times
     *
     * @param loginTimes the value for admin.login_times
     *
     * @mbg.generated
     */
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.realname
     *
     * @return the value of admin.realname
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.realname
     *
     * @param realname the value for admin.realname
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.rank0
     *
     * @return the value of admin.rank0
     *
     * @mbg.generated
     */
    public Boolean getRank0() {
        return rank0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.rank0
     *
     * @param rank0 the value for admin.rank0
     *
     * @mbg.generated
     */
    public void setRank0(Boolean rank0) {
        this.rank0 = rank0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.rank1
     *
     * @return the value of admin.rank1
     *
     * @mbg.generated
     */
    public Boolean getRank1() {
        return rank1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.rank1
     *
     * @param rank1 the value for admin.rank1
     *
     * @mbg.generated
     */
    public void setRank1(Boolean rank1) {
        this.rank1 = rank1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.rank2
     *
     * @return the value of admin.rank2
     *
     * @mbg.generated
     */
    public Boolean getRank2() {
        return rank2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.rank2
     *
     * @param rank2 the value for admin.rank2
     *
     * @mbg.generated
     */
    public void setRank2(Boolean rank2) {
        this.rank2 = rank2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.rank3
     *
     * @return the value of admin.rank3
     *
     * @mbg.generated
     */
    public Boolean getRank3() {
        return rank3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.rank3
     *
     * @param rank3 the value for admin.rank3
     *
     * @mbg.generated
     */
    public void setRank3(Boolean rank3) {
        this.rank3 = rank3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.rank4
     *
     * @return the value of admin.rank4
     *
     * @mbg.generated
     */
    public Boolean getRank4() {
        return rank4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.rank4
     *
     * @param rank4 the value for admin.rank4
     *
     * @mbg.generated
     */
    public void setRank4(Boolean rank4) {
        this.rank4 = rank4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.rank5
     *
     * @return the value of admin.rank5
     *
     * @mbg.generated
     */
    public Boolean getRank5() {
        return rank5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.rank5
     *
     * @param rank5 the value for admin.rank5
     *
     * @mbg.generated
     */
    public void setRank5(Boolean rank5) {
        this.rank5 = rank5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.rank6
     *
     * @return the value of admin.rank6
     *
     * @mbg.generated
     */
    public Boolean getRank6() {
        return rank6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.rank6
     *
     * @param rank6 the value for admin.rank6
     *
     * @mbg.generated
     */
    public void setRank6(Boolean rank6) {
        this.rank6 = rank6;
    }
}