package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table linktype
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Linktype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linktype.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linktype.typename
     *
     * @mbg.generated
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linktype.paixu
     *
     * @mbg.generated
     */
    private Integer paixu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linktype.id
     *
     * @return the value of linktype.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linktype.id
     *
     * @param id the value for linktype.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linktype.typename
     *
     * @return the value of linktype.typename
     *
     * @mbg.generated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linktype.typename
     *
     * @param typename the value for linktype.typename
     *
     * @mbg.generated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linktype.paixu
     *
     * @return the value of linktype.paixu
     *
     * @mbg.generated
     */
    public Integer getPaixu() {
        return paixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linktype.paixu
     *
     * @param paixu the value for linktype.paixu
     *
     * @mbg.generated
     */
    public void setPaixu(Integer paixu) {
        this.paixu = paixu;
    }
}