package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table link
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Link {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.typeid
     *
     * @mbg.generated
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.paixu
     *
     * @mbg.generated
     */
    private Integer paixu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.ifshow
     *
     * @mbg.generated
     */
    private Boolean ifshow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.id
     *
     * @return the value of link.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.id
     *
     * @param id the value for link.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.title
     *
     * @return the value of link.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.title
     *
     * @param title the value for link.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.typeid
     *
     * @return the value of link.typeid
     *
     * @mbg.generated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.typeid
     *
     * @param typeid the value for link.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.pic
     *
     * @return the value of link.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.pic
     *
     * @param pic the value for link.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.paixu
     *
     * @return the value of link.paixu
     *
     * @mbg.generated
     */
    public Integer getPaixu() {
        return paixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.paixu
     *
     * @param paixu the value for link.paixu
     *
     * @mbg.generated
     */
    public void setPaixu(Integer paixu) {
        this.paixu = paixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.url
     *
     * @return the value of link.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.url
     *
     * @param url the value for link.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.ifshow
     *
     * @return the value of link.ifshow
     *
     * @mbg.generated
     */
    public Boolean getIfshow() {
        return ifshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.ifshow
     *
     * @param ifshow the value for link.ifshow
     *
     * @mbg.generated
     */
    public void setIfshow(Boolean ifshow) {
        this.ifshow = ifshow;
    }
}