package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table newstype
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Newstype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.typename
     *
     * @mbg.generated
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.foldername
     *
     * @mbg.generated
     */
    private String foldername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.typetemp
     *
     * @mbg.generated
     */
    private String typetemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.contenttemp
     *
     * @mbg.generated
     */
    private String contenttemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.classtype
     *
     * @mbg.generated
     */
    private Byte classtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.keycontent
     *
     * @mbg.generated
     */
    private String keycontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.paixu
     *
     * @mbg.generated
     */
    private Integer paixu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.picsif
     *
     * @mbg.generated
     */
    private Boolean picsif;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.jibie
     *
     * @mbg.generated
     */
    private Byte jibie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.linkaddr
     *
     * @mbg.generated
     */
    private Boolean linkaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.typelink
     *
     * @mbg.generated
     */
    private String typelink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.id
     *
     * @return the value of newstype.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.id
     *
     * @param id the value for newstype.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.typename
     *
     * @return the value of newstype.typename
     *
     * @mbg.generated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.typename
     *
     * @param typename the value for newstype.typename
     *
     * @mbg.generated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.foldername
     *
     * @return the value of newstype.foldername
     *
     * @mbg.generated
     */
    public String getFoldername() {
        return foldername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.foldername
     *
     * @param foldername the value for newstype.foldername
     *
     * @mbg.generated
     */
    public void setFoldername(String foldername) {
        this.foldername = foldername == null ? null : foldername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.typetemp
     *
     * @return the value of newstype.typetemp
     *
     * @mbg.generated
     */
    public String getTypetemp() {
        return typetemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.typetemp
     *
     * @param typetemp the value for newstype.typetemp
     *
     * @mbg.generated
     */
    public void setTypetemp(String typetemp) {
        this.typetemp = typetemp == null ? null : typetemp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.contenttemp
     *
     * @return the value of newstype.contenttemp
     *
     * @mbg.generated
     */
    public String getContenttemp() {
        return contenttemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.contenttemp
     *
     * @param contenttemp the value for newstype.contenttemp
     *
     * @mbg.generated
     */
    public void setContenttemp(String contenttemp) {
        this.contenttemp = contenttemp == null ? null : contenttemp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.classtype
     *
     * @return the value of newstype.classtype
     *
     * @mbg.generated
     */
    public Byte getClasstype() {
        return classtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.classtype
     *
     * @param classtype the value for newstype.classtype
     *
     * @mbg.generated
     */
    public void setClasstype(Byte classtype) {
        this.classtype = classtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.keywords
     *
     * @return the value of newstype.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.keywords
     *
     * @param keywords the value for newstype.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.keycontent
     *
     * @return the value of newstype.keycontent
     *
     * @mbg.generated
     */
    public String getKeycontent() {
        return keycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.keycontent
     *
     * @param keycontent the value for newstype.keycontent
     *
     * @mbg.generated
     */
    public void setKeycontent(String keycontent) {
        this.keycontent = keycontent == null ? null : keycontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.paixu
     *
     * @return the value of newstype.paixu
     *
     * @mbg.generated
     */
    public Integer getPaixu() {
        return paixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.paixu
     *
     * @param paixu the value for newstype.paixu
     *
     * @mbg.generated
     */
    public void setPaixu(Integer paixu) {
        this.paixu = paixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.picsif
     *
     * @return the value of newstype.picsif
     *
     * @mbg.generated
     */
    public Boolean getPicsif() {
        return picsif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.picsif
     *
     * @param picsif the value for newstype.picsif
     *
     * @mbg.generated
     */
    public void setPicsif(Boolean picsif) {
        this.picsif = picsif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.cid
     *
     * @return the value of newstype.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.cid
     *
     * @param cid the value for newstype.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.jibie
     *
     * @return the value of newstype.jibie
     *
     * @mbg.generated
     */
    public Byte getJibie() {
        return jibie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.jibie
     *
     * @param jibie the value for newstype.jibie
     *
     * @mbg.generated
     */
    public void setJibie(Byte jibie) {
        this.jibie = jibie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.linkaddr
     *
     * @return the value of newstype.linkaddr
     *
     * @mbg.generated
     */
    public Boolean getLinkaddr() {
        return linkaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.linkaddr
     *
     * @param linkaddr the value for newstype.linkaddr
     *
     * @mbg.generated
     */
    public void setLinkaddr(Boolean linkaddr) {
        this.linkaddr = linkaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.typelink
     *
     * @return the value of newstype.typelink
     *
     * @mbg.generated
     */
    public String getTypelink() {
        return typelink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.typelink
     *
     * @param typelink the value for newstype.typelink
     *
     * @mbg.generated
     */
    public void setTypelink(String typelink) {
        this.typelink = typelink == null ? null : typelink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.content
     *
     * @return the value of newstype.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.content
     *
     * @param content the value for newstype.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}