package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table newsimg
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Newsimg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsimg.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsimg.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsimg.imgsrc
     *
     * @mbg.generated
     */
    private String imgsrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsimg.newsid
     *
     * @mbg.generated
     */
    private Integer newsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsimg.paixu
     *
     * @mbg.generated
     */
    private Integer paixu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsimg.id
     *
     * @return the value of newsimg.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsimg.id
     *
     * @param id the value for newsimg.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsimg.title
     *
     * @return the value of newsimg.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsimg.title
     *
     * @param title the value for newsimg.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsimg.imgsrc
     *
     * @return the value of newsimg.imgsrc
     *
     * @mbg.generated
     */
    public String getImgsrc() {
        return imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsimg.imgsrc
     *
     * @param imgsrc the value for newsimg.imgsrc
     *
     * @mbg.generated
     */
    public void setImgsrc(String imgsrc) {
        this.imgsrc = imgsrc == null ? null : imgsrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsimg.newsid
     *
     * @return the value of newsimg.newsid
     *
     * @mbg.generated
     */
    public Integer getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsimg.newsid
     *
     * @param newsid the value for newsimg.newsid
     *
     * @mbg.generated
     */
    public void setNewsid(Integer newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsimg.paixu
     *
     * @return the value of newsimg.paixu
     *
     * @mbg.generated
     */
    public Integer getPaixu() {
        return paixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsimg.paixu
     *
     * @param paixu the value for newsimg.paixu
     *
     * @mbg.generated
     */
    public void setPaixu(Integer paixu) {
        this.paixu = paixu;
    }
}