package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table newsplus
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Newsplus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsplus.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsplus.typeid
     *
     * @mbg.generated
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsplus.zdtip
     *
     * @mbg.generated
     */
    private String zdtip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsplus.zdname
     *
     * @mbg.generated
     */
    private String zdname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsplus.zdtype
     *
     * @mbg.generated
     */
    private Integer zdtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsplus.zdcontent
     *
     * @mbg.generated
     */
    private String zdcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsplus.id
     *
     * @return the value of newsplus.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsplus.id
     *
     * @param id the value for newsplus.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsplus.typeid
     *
     * @return the value of newsplus.typeid
     *
     * @mbg.generated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsplus.typeid
     *
     * @param typeid the value for newsplus.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsplus.zdtip
     *
     * @return the value of newsplus.zdtip
     *
     * @mbg.generated
     */
    public String getZdtip() {
        return zdtip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsplus.zdtip
     *
     * @param zdtip the value for newsplus.zdtip
     *
     * @mbg.generated
     */
    public void setZdtip(String zdtip) {
        this.zdtip = zdtip == null ? null : zdtip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsplus.zdname
     *
     * @return the value of newsplus.zdname
     *
     * @mbg.generated
     */
    public String getZdname() {
        return zdname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsplus.zdname
     *
     * @param zdname the value for newsplus.zdname
     *
     * @mbg.generated
     */
    public void setZdname(String zdname) {
        this.zdname = zdname == null ? null : zdname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsplus.zdtype
     *
     * @return the value of newsplus.zdtype
     *
     * @mbg.generated
     */
    public Integer getZdtype() {
        return zdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsplus.zdtype
     *
     * @param zdtype the value for newsplus.zdtype
     *
     * @mbg.generated
     */
    public void setZdtype(Integer zdtype) {
        this.zdtype = zdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsplus.zdcontent
     *
     * @return the value of newsplus.zdcontent
     *
     * @mbg.generated
     */
    public String getZdcontent() {
        return zdcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsplus.zdcontent
     *
     * @param zdcontent the value for newsplus.zdcontent
     *
     * @mbg.generated
     */
    public void setZdcontent(String zdcontent) {
        this.zdcontent = zdcontent == null ? null : zdcontent.trim();
    }
}