package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table news
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.shorttitle
     *
     * @mbg.generated
     */
    private String shorttitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.typeid
     *
     * @mbg.generated
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.smallpic
     *
     * @mbg.generated
     */
    private String smallpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.bigpic
     *
     * @mbg.generated
     */
    private String bigpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.keycontent
     *
     * @mbg.generated
     */
    private String keycontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.addtime
     *
     * @mbg.generated
     */
    private Integer addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.edittime
     *
     * @mbg.generated
     */
    private Integer edittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.paixu
     *
     * @mbg.generated
     */
    private Integer paixu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.readtimes
     *
     * @mbg.generated
     */
    private Integer readtimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.iftop
     *
     * @mbg.generated
     */
    private Boolean iftop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.ifflash
     *
     * @mbg.generated
     */
    private Boolean ifflash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.foldername
     *
     * @mbg.generated
     */
    private String foldername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.shorttitle
     *
     * @return the value of news.shorttitle
     *
     * @mbg.generated
     */
    public String getShorttitle() {
        return shorttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.shorttitle
     *
     * @param shorttitle the value for news.shorttitle
     *
     * @mbg.generated
     */
    public void setShorttitle(String shorttitle) {
        this.shorttitle = shorttitle == null ? null : shorttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.typeid
     *
     * @return the value of news.typeid
     *
     * @mbg.generated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.typeid
     *
     * @param typeid the value for news.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.smallpic
     *
     * @return the value of news.smallpic
     *
     * @mbg.generated
     */
    public String getSmallpic() {
        return smallpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.smallpic
     *
     * @param smallpic the value for news.smallpic
     *
     * @mbg.generated
     */
    public void setSmallpic(String smallpic) {
        this.smallpic = smallpic == null ? null : smallpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.bigpic
     *
     * @return the value of news.bigpic
     *
     * @mbg.generated
     */
    public String getBigpic() {
        return bigpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.bigpic
     *
     * @param bigpic the value for news.bigpic
     *
     * @mbg.generated
     */
    public void setBigpic(String bigpic) {
        this.bigpic = bigpic == null ? null : bigpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.keywords
     *
     * @return the value of news.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.keywords
     *
     * @param keywords the value for news.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.keycontent
     *
     * @return the value of news.keycontent
     *
     * @mbg.generated
     */
    public String getKeycontent() {
        return keycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.keycontent
     *
     * @param keycontent the value for news.keycontent
     *
     * @mbg.generated
     */
    public void setKeycontent(String keycontent) {
        this.keycontent = keycontent == null ? null : keycontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.author
     *
     * @return the value of news.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.author
     *
     * @param author the value for news.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.source
     *
     * @return the value of news.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.source
     *
     * @param source the value for news.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.addtime
     *
     * @return the value of news.addtime
     *
     * @mbg.generated
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.addtime
     *
     * @param addtime the value for news.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.edittime
     *
     * @return the value of news.edittime
     *
     * @mbg.generated
     */
    public Integer getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.edittime
     *
     * @param edittime the value for news.edittime
     *
     * @mbg.generated
     */
    public void setEdittime(Integer edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.paixu
     *
     * @return the value of news.paixu
     *
     * @mbg.generated
     */
    public Integer getPaixu() {
        return paixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.paixu
     *
     * @param paixu the value for news.paixu
     *
     * @mbg.generated
     */
    public void setPaixu(Integer paixu) {
        this.paixu = paixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.readtimes
     *
     * @return the value of news.readtimes
     *
     * @mbg.generated
     */
    public Integer getReadtimes() {
        return readtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.readtimes
     *
     * @param readtimes the value for news.readtimes
     *
     * @mbg.generated
     */
    public void setReadtimes(Integer readtimes) {
        this.readtimes = readtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.iftop
     *
     * @return the value of news.iftop
     *
     * @mbg.generated
     */
    public Boolean getIftop() {
        return iftop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.iftop
     *
     * @param iftop the value for news.iftop
     *
     * @mbg.generated
     */
    public void setIftop(Boolean iftop) {
        this.iftop = iftop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.ifflash
     *
     * @return the value of news.ifflash
     *
     * @mbg.generated
     */
    public Boolean getIfflash() {
        return ifflash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.ifflash
     *
     * @param ifflash the value for news.ifflash
     *
     * @mbg.generated
     */
    public void setIfflash(Boolean ifflash) {
        this.ifflash = ifflash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.foldername
     *
     * @return the value of news.foldername
     *
     * @mbg.generated
     */
    public String getFoldername() {
        return foldername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.foldername
     *
     * @param foldername the value for news.foldername
     *
     * @mbg.generated
     */
    public void setFoldername(String foldername) {
        this.foldername = foldername == null ? null : foldername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}