package test.model;

import java.util.ArrayList;
import java.util.List;

public class NewsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public NewsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andShorttitleIsNull() {
            addCriterion("shorttitle is null");
            return (Criteria) this;
        }

        public Criteria andShorttitleIsNotNull() {
            addCriterion("shorttitle is not null");
            return (Criteria) this;
        }

        public Criteria andShorttitleEqualTo(String value) {
            addCriterion("shorttitle =", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleNotEqualTo(String value) {
            addCriterion("shorttitle <>", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleGreaterThan(String value) {
            addCriterion("shorttitle >", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleGreaterThanOrEqualTo(String value) {
            addCriterion("shorttitle >=", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleLessThan(String value) {
            addCriterion("shorttitle <", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleLessThanOrEqualTo(String value) {
            addCriterion("shorttitle <=", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleLike(String value) {
            addCriterion("shorttitle like", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleNotLike(String value) {
            addCriterion("shorttitle not like", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleIn(List<String> values) {
            addCriterion("shorttitle in", values, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleNotIn(List<String> values) {
            addCriterion("shorttitle not in", values, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleBetween(String value1, String value2) {
            addCriterion("shorttitle between", value1, value2, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleNotBetween(String value1, String value2) {
            addCriterion("shorttitle not between", value1, value2, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNull() {
            addCriterion("typeid is null");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNotNull() {
            addCriterion("typeid is not null");
            return (Criteria) this;
        }

        public Criteria andTypeidEqualTo(Integer value) {
            addCriterion("typeid =", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotEqualTo(Integer value) {
            addCriterion("typeid <>", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThan(Integer value) {
            addCriterion("typeid >", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("typeid >=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThan(Integer value) {
            addCriterion("typeid <", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThanOrEqualTo(Integer value) {
            addCriterion("typeid <=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidIn(List<Integer> values) {
            addCriterion("typeid in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotIn(List<Integer> values) {
            addCriterion("typeid not in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidBetween(Integer value1, Integer value2) {
            addCriterion("typeid between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("typeid not between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andSmallpicIsNull() {
            addCriterion("smallpic is null");
            return (Criteria) this;
        }

        public Criteria andSmallpicIsNotNull() {
            addCriterion("smallpic is not null");
            return (Criteria) this;
        }

        public Criteria andSmallpicEqualTo(String value) {
            addCriterion("smallpic =", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicNotEqualTo(String value) {
            addCriterion("smallpic <>", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicGreaterThan(String value) {
            addCriterion("smallpic >", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicGreaterThanOrEqualTo(String value) {
            addCriterion("smallpic >=", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicLessThan(String value) {
            addCriterion("smallpic <", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicLessThanOrEqualTo(String value) {
            addCriterion("smallpic <=", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicLike(String value) {
            addCriterion("smallpic like", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicNotLike(String value) {
            addCriterion("smallpic not like", value, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicIn(List<String> values) {
            addCriterion("smallpic in", values, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicNotIn(List<String> values) {
            addCriterion("smallpic not in", values, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicBetween(String value1, String value2) {
            addCriterion("smallpic between", value1, value2, "smallpic");
            return (Criteria) this;
        }

        public Criteria andSmallpicNotBetween(String value1, String value2) {
            addCriterion("smallpic not between", value1, value2, "smallpic");
            return (Criteria) this;
        }

        public Criteria andBigpicIsNull() {
            addCriterion("bigpic is null");
            return (Criteria) this;
        }

        public Criteria andBigpicIsNotNull() {
            addCriterion("bigpic is not null");
            return (Criteria) this;
        }

        public Criteria andBigpicEqualTo(String value) {
            addCriterion("bigpic =", value, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicNotEqualTo(String value) {
            addCriterion("bigpic <>", value, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicGreaterThan(String value) {
            addCriterion("bigpic >", value, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicGreaterThanOrEqualTo(String value) {
            addCriterion("bigpic >=", value, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicLessThan(String value) {
            addCriterion("bigpic <", value, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicLessThanOrEqualTo(String value) {
            addCriterion("bigpic <=", value, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicLike(String value) {
            addCriterion("bigpic like", value, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicNotLike(String value) {
            addCriterion("bigpic not like", value, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicIn(List<String> values) {
            addCriterion("bigpic in", values, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicNotIn(List<String> values) {
            addCriterion("bigpic not in", values, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicBetween(String value1, String value2) {
            addCriterion("bigpic between", value1, value2, "bigpic");
            return (Criteria) this;
        }

        public Criteria andBigpicNotBetween(String value1, String value2) {
            addCriterion("bigpic not between", value1, value2, "bigpic");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeycontentIsNull() {
            addCriterion("keycontent is null");
            return (Criteria) this;
        }

        public Criteria andKeycontentIsNotNull() {
            addCriterion("keycontent is not null");
            return (Criteria) this;
        }

        public Criteria andKeycontentEqualTo(String value) {
            addCriterion("keycontent =", value, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentNotEqualTo(String value) {
            addCriterion("keycontent <>", value, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentGreaterThan(String value) {
            addCriterion("keycontent >", value, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentGreaterThanOrEqualTo(String value) {
            addCriterion("keycontent >=", value, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentLessThan(String value) {
            addCriterion("keycontent <", value, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentLessThanOrEqualTo(String value) {
            addCriterion("keycontent <=", value, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentLike(String value) {
            addCriterion("keycontent like", value, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentNotLike(String value) {
            addCriterion("keycontent not like", value, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentIn(List<String> values) {
            addCriterion("keycontent in", values, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentNotIn(List<String> values) {
            addCriterion("keycontent not in", values, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentBetween(String value1, String value2) {
            addCriterion("keycontent between", value1, value2, "keycontent");
            return (Criteria) this;
        }

        public Criteria andKeycontentNotBetween(String value1, String value2) {
            addCriterion("keycontent not between", value1, value2, "keycontent");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("addtime is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("addtime is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(Integer value) {
            addCriterion("addtime =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(Integer value) {
            addCriterion("addtime <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(Integer value) {
            addCriterion("addtime >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("addtime >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(Integer value) {
            addCriterion("addtime <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(Integer value) {
            addCriterion("addtime <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<Integer> values) {
            addCriterion("addtime in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<Integer> values) {
            addCriterion("addtime not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(Integer value1, Integer value2) {
            addCriterion("addtime between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("addtime not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andEdittimeIsNull() {
            addCriterion("edittime is null");
            return (Criteria) this;
        }

        public Criteria andEdittimeIsNotNull() {
            addCriterion("edittime is not null");
            return (Criteria) this;
        }

        public Criteria andEdittimeEqualTo(Integer value) {
            addCriterion("edittime =", value, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeNotEqualTo(Integer value) {
            addCriterion("edittime <>", value, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeGreaterThan(Integer value) {
            addCriterion("edittime >", value, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("edittime >=", value, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeLessThan(Integer value) {
            addCriterion("edittime <", value, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeLessThanOrEqualTo(Integer value) {
            addCriterion("edittime <=", value, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeIn(List<Integer> values) {
            addCriterion("edittime in", values, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeNotIn(List<Integer> values) {
            addCriterion("edittime not in", values, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeBetween(Integer value1, Integer value2) {
            addCriterion("edittime between", value1, value2, "edittime");
            return (Criteria) this;
        }

        public Criteria andEdittimeNotBetween(Integer value1, Integer value2) {
            addCriterion("edittime not between", value1, value2, "edittime");
            return (Criteria) this;
        }

        public Criteria andPaixuIsNull() {
            addCriterion("paixu is null");
            return (Criteria) this;
        }

        public Criteria andPaixuIsNotNull() {
            addCriterion("paixu is not null");
            return (Criteria) this;
        }

        public Criteria andPaixuEqualTo(Integer value) {
            addCriterion("paixu =", value, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuNotEqualTo(Integer value) {
            addCriterion("paixu <>", value, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuGreaterThan(Integer value) {
            addCriterion("paixu >", value, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuGreaterThanOrEqualTo(Integer value) {
            addCriterion("paixu >=", value, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuLessThan(Integer value) {
            addCriterion("paixu <", value, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuLessThanOrEqualTo(Integer value) {
            addCriterion("paixu <=", value, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuIn(List<Integer> values) {
            addCriterion("paixu in", values, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuNotIn(List<Integer> values) {
            addCriterion("paixu not in", values, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuBetween(Integer value1, Integer value2) {
            addCriterion("paixu between", value1, value2, "paixu");
            return (Criteria) this;
        }

        public Criteria andPaixuNotBetween(Integer value1, Integer value2) {
            addCriterion("paixu not between", value1, value2, "paixu");
            return (Criteria) this;
        }

        public Criteria andReadtimesIsNull() {
            addCriterion("readtimes is null");
            return (Criteria) this;
        }

        public Criteria andReadtimesIsNotNull() {
            addCriterion("readtimes is not null");
            return (Criteria) this;
        }

        public Criteria andReadtimesEqualTo(Integer value) {
            addCriterion("readtimes =", value, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesNotEqualTo(Integer value) {
            addCriterion("readtimes <>", value, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesGreaterThan(Integer value) {
            addCriterion("readtimes >", value, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("readtimes >=", value, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesLessThan(Integer value) {
            addCriterion("readtimes <", value, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesLessThanOrEqualTo(Integer value) {
            addCriterion("readtimes <=", value, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesIn(List<Integer> values) {
            addCriterion("readtimes in", values, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesNotIn(List<Integer> values) {
            addCriterion("readtimes not in", values, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesBetween(Integer value1, Integer value2) {
            addCriterion("readtimes between", value1, value2, "readtimes");
            return (Criteria) this;
        }

        public Criteria andReadtimesNotBetween(Integer value1, Integer value2) {
            addCriterion("readtimes not between", value1, value2, "readtimes");
            return (Criteria) this;
        }

        public Criteria andIftopIsNull() {
            addCriterion("iftop is null");
            return (Criteria) this;
        }

        public Criteria andIftopIsNotNull() {
            addCriterion("iftop is not null");
            return (Criteria) this;
        }

        public Criteria andIftopEqualTo(Boolean value) {
            addCriterion("iftop =", value, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopNotEqualTo(Boolean value) {
            addCriterion("iftop <>", value, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopGreaterThan(Boolean value) {
            addCriterion("iftop >", value, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopGreaterThanOrEqualTo(Boolean value) {
            addCriterion("iftop >=", value, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopLessThan(Boolean value) {
            addCriterion("iftop <", value, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopLessThanOrEqualTo(Boolean value) {
            addCriterion("iftop <=", value, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopIn(List<Boolean> values) {
            addCriterion("iftop in", values, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopNotIn(List<Boolean> values) {
            addCriterion("iftop not in", values, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopBetween(Boolean value1, Boolean value2) {
            addCriterion("iftop between", value1, value2, "iftop");
            return (Criteria) this;
        }

        public Criteria andIftopNotBetween(Boolean value1, Boolean value2) {
            addCriterion("iftop not between", value1, value2, "iftop");
            return (Criteria) this;
        }

        public Criteria andIfflashIsNull() {
            addCriterion("ifflash is null");
            return (Criteria) this;
        }

        public Criteria andIfflashIsNotNull() {
            addCriterion("ifflash is not null");
            return (Criteria) this;
        }

        public Criteria andIfflashEqualTo(Boolean value) {
            addCriterion("ifflash =", value, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashNotEqualTo(Boolean value) {
            addCriterion("ifflash <>", value, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashGreaterThan(Boolean value) {
            addCriterion("ifflash >", value, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ifflash >=", value, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashLessThan(Boolean value) {
            addCriterion("ifflash <", value, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashLessThanOrEqualTo(Boolean value) {
            addCriterion("ifflash <=", value, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashIn(List<Boolean> values) {
            addCriterion("ifflash in", values, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashNotIn(List<Boolean> values) {
            addCriterion("ifflash not in", values, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashBetween(Boolean value1, Boolean value2) {
            addCriterion("ifflash between", value1, value2, "ifflash");
            return (Criteria) this;
        }

        public Criteria andIfflashNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ifflash not between", value1, value2, "ifflash");
            return (Criteria) this;
        }

        public Criteria andFoldernameIsNull() {
            addCriterion("foldername is null");
            return (Criteria) this;
        }

        public Criteria andFoldernameIsNotNull() {
            addCriterion("foldername is not null");
            return (Criteria) this;
        }

        public Criteria andFoldernameEqualTo(String value) {
            addCriterion("foldername =", value, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameNotEqualTo(String value) {
            addCriterion("foldername <>", value, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameGreaterThan(String value) {
            addCriterion("foldername >", value, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameGreaterThanOrEqualTo(String value) {
            addCriterion("foldername >=", value, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameLessThan(String value) {
            addCriterion("foldername <", value, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameLessThanOrEqualTo(String value) {
            addCriterion("foldername <=", value, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameLike(String value) {
            addCriterion("foldername like", value, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameNotLike(String value) {
            addCriterion("foldername not like", value, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameIn(List<String> values) {
            addCriterion("foldername in", values, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameNotIn(List<String> values) {
            addCriterion("foldername not in", values, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameBetween(String value1, String value2) {
            addCriterion("foldername between", value1, value2, "foldername");
            return (Criteria) this;
        }

        public Criteria andFoldernameNotBetween(String value1, String value2) {
            addCriterion("foldername not between", value1, value2, "foldername");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}