package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sysinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Sysinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.keycontent
     *
     * @mbg.generated
     */
    private String keycontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.weburl
     *
     * @mbg.generated
     */
    private String weburl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.contacter
     *
     * @mbg.generated
     */
    private String contacter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.weixin
     *
     * @mbg.generated
     */
    private String weixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.erweima
     *
     * @mbg.generated
     */
    private String erweima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.beianhao
     *
     * @mbg.generated
     */
    private String beianhao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.jianjie
     *
     * @mbg.generated
     */
    private String jianjie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.tongji
     *
     * @mbg.generated
     */
    private String tongji;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.id
     *
     * @return the value of sysinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.id
     *
     * @param id the value for sysinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.title
     *
     * @return the value of sysinfo.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.title
     *
     * @param title the value for sysinfo.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.keywords
     *
     * @return the value of sysinfo.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.keywords
     *
     * @param keywords the value for sysinfo.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.keycontent
     *
     * @return the value of sysinfo.keycontent
     *
     * @mbg.generated
     */
    public String getKeycontent() {
        return keycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.keycontent
     *
     * @param keycontent the value for sysinfo.keycontent
     *
     * @mbg.generated
     */
    public void setKeycontent(String keycontent) {
        this.keycontent = keycontent == null ? null : keycontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.weburl
     *
     * @return the value of sysinfo.weburl
     *
     * @mbg.generated
     */
    public String getWeburl() {
        return weburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.weburl
     *
     * @param weburl the value for sysinfo.weburl
     *
     * @mbg.generated
     */
    public void setWeburl(String weburl) {
        this.weburl = weburl == null ? null : weburl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.logo
     *
     * @return the value of sysinfo.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.logo
     *
     * @param logo the value for sysinfo.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.address
     *
     * @return the value of sysinfo.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.address
     *
     * @param address the value for sysinfo.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.contacter
     *
     * @return the value of sysinfo.contacter
     *
     * @mbg.generated
     */
    public String getContacter() {
        return contacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.contacter
     *
     * @param contacter the value for sysinfo.contacter
     *
     * @mbg.generated
     */
    public void setContacter(String contacter) {
        this.contacter = contacter == null ? null : contacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.tel
     *
     * @return the value of sysinfo.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.tel
     *
     * @param tel the value for sysinfo.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.fax
     *
     * @return the value of sysinfo.fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.fax
     *
     * @param fax the value for sysinfo.fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.email
     *
     * @return the value of sysinfo.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.email
     *
     * @param email the value for sysinfo.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.weixin
     *
     * @return the value of sysinfo.weixin
     *
     * @mbg.generated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.weixin
     *
     * @param weixin the value for sysinfo.weixin
     *
     * @mbg.generated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.erweima
     *
     * @return the value of sysinfo.erweima
     *
     * @mbg.generated
     */
    public String getErweima() {
        return erweima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.erweima
     *
     * @param erweima the value for sysinfo.erweima
     *
     * @mbg.generated
     */
    public void setErweima(String erweima) {
        this.erweima = erweima == null ? null : erweima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.beianhao
     *
     * @return the value of sysinfo.beianhao
     *
     * @mbg.generated
     */
    public String getBeianhao() {
        return beianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.beianhao
     *
     * @param beianhao the value for sysinfo.beianhao
     *
     * @mbg.generated
     */
    public void setBeianhao(String beianhao) {
        this.beianhao = beianhao == null ? null : beianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.jianjie
     *
     * @return the value of sysinfo.jianjie
     *
     * @mbg.generated
     */
    public String getJianjie() {
        return jianjie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.jianjie
     *
     * @param jianjie the value for sysinfo.jianjie
     *
     * @mbg.generated
     */
    public void setJianjie(String jianjie) {
        this.jianjie = jianjie == null ? null : jianjie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.tongji
     *
     * @return the value of sysinfo.tongji
     *
     * @mbg.generated
     */
    public String getTongji() {
        return tongji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.tongji
     *
     * @param tongji the value for sysinfo.tongji
     *
     * @mbg.generated
     */
    public void setTongji(String tongji) {
        this.tongji = tongji == null ? null : tongji.trim();
    }
}