package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table syslog
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Syslog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.logtype
     *
     * @mbg.generated
     */
    private Byte logtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.logtitle
     *
     * @mbg.generated
     */
    private String logtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.admin
     *
     * @mbg.generated
     */
    private String admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.newsid
     *
     * @mbg.generated
     */
    private Integer newsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.newstitle
     *
     * @mbg.generated
     */
    private String newstitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.dateandtime
     *
     * @mbg.generated
     */
    private Integer dateandtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.id
     *
     * @return the value of syslog.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.id
     *
     * @param id the value for syslog.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.logtype
     *
     * @return the value of syslog.logtype
     *
     * @mbg.generated
     */
    public Byte getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.logtype
     *
     * @param logtype the value for syslog.logtype
     *
     * @mbg.generated
     */
    public void setLogtype(Byte logtype) {
        this.logtype = logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.logtitle
     *
     * @return the value of syslog.logtitle
     *
     * @mbg.generated
     */
    public String getLogtitle() {
        return logtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.logtitle
     *
     * @param logtitle the value for syslog.logtitle
     *
     * @mbg.generated
     */
    public void setLogtitle(String logtitle) {
        this.logtitle = logtitle == null ? null : logtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.admin
     *
     * @return the value of syslog.admin
     *
     * @mbg.generated
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.admin
     *
     * @param admin the value for syslog.admin
     *
     * @mbg.generated
     */
    public void setAdmin(String admin) {
        this.admin = admin == null ? null : admin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.newsid
     *
     * @return the value of syslog.newsid
     *
     * @mbg.generated
     */
    public Integer getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.newsid
     *
     * @param newsid the value for syslog.newsid
     *
     * @mbg.generated
     */
    public void setNewsid(Integer newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.newstitle
     *
     * @return the value of syslog.newstitle
     *
     * @mbg.generated
     */
    public String getNewstitle() {
        return newstitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.newstitle
     *
     * @param newstitle the value for syslog.newstitle
     *
     * @mbg.generated
     */
    public void setNewstitle(String newstitle) {
        this.newstitle = newstitle == null ? null : newstitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.dateandtime
     *
     * @return the value of syslog.dateandtime
     *
     * @mbg.generated
     */
    public Integer getDateandtime() {
        return dateandtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.dateandtime
     *
     * @param dateandtime the value for syslog.dateandtime
     *
     * @mbg.generated
     */
    public void setDateandtime(Integer dateandtime) {
        this.dateandtime = dateandtime;
    }
}