package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Ads;
import test.model.AdsExample;

public interface AdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    long countByExample(AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int deleteByExample(AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int insert(Ads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int insertSelective(Ads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    List<Ads> selectByExample(AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    Ads selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ads record, @Param("example") AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ads record, @Param("example") AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ads record);
}