package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Adtype;
import test.model.AdtypeExample;

public interface AdtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    long countByExample(AdtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    int deleteByExample(AdtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    int insert(Adtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    int insertSelective(Adtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    List<Adtype> selectByExample(AdtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    Adtype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Adtype record, @Param("example") AdtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Adtype record, @Param("example") AdtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Adtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Adtype record);
}