package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Linktype;
import test.model.LinktypeExample;

public interface LinktypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    long countByExample(LinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    int deleteByExample(LinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    int insert(Linktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    int insertSelective(Linktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    List<Linktype> selectByExample(LinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    Linktype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Linktype record, @Param("example") LinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Linktype record, @Param("example") LinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Linktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linktype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Linktype record);
}