package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Newsplus;
import test.model.NewsplusExample;

public interface NewsplusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    long countByExample(NewsplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    int deleteByExample(NewsplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    int insert(Newsplus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    int insertSelective(Newsplus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    List<Newsplus> selectByExample(NewsplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    Newsplus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Newsplus record, @Param("example") NewsplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Newsplus record, @Param("example") NewsplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Newsplus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsplus
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Newsplus record);
}