package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Newsimg;
import test.model.NewsimgExample;

public interface NewsimgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    long countByExample(NewsimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    int deleteByExample(NewsimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    int insert(Newsimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    int insertSelective(Newsimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    List<Newsimg> selectByExample(NewsimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    Newsimg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Newsimg record, @Param("example") NewsimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Newsimg record, @Param("example") NewsimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Newsimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsimg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Newsimg record);
}