package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Newstype;
import test.model.NewstypeExample;

public interface NewstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    long countByExample(NewstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int deleteByExample(NewstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int insert(Newstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int insertSelective(Newstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    List<Newstype> selectByExampleWithBLOBs(NewstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    List<Newstype> selectByExample(NewstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    Newstype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Newstype record, @Param("example") NewstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Newstype record, @Param("example") NewstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Newstype record, @Param("example") NewstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Newstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Newstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Newstype record);
}