package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Sysinfo;
import test.model.SysinfoExample;

public interface SysinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    long countByExample(SysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int deleteByExample(SysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int insert(Sysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int insertSelective(Sysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    List<Sysinfo> selectByExampleWithBLOBs(SysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    List<Sysinfo> selectByExample(SysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    Sysinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sysinfo record, @Param("example") SysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Sysinfo record, @Param("example") SysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sysinfo record, @Param("example") SysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Sysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sysinfo record);
}