package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Syslog;
import test.model.SyslogExample;

public interface SyslogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    long countByExample(SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    int deleteByExample(SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    int insert(Syslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    int insertSelective(Syslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    List<Syslog> selectByExample(SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    Syslog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Syslog record, @Param("example") SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Syslog record, @Param("example") SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syslog record);
}